config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jobs#index'
  resources :jobs

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  def hidden?
    is_hidden
  end

  def publish!
    self.update_columns(:is_hidden => false)
    # self.is_hidden = false
    # self.save
  end

  def hide!
    self.update_columns(:is_hidden => true)
    # self.is_hidden = true
    # self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "工作更新成功"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path, alert: "工作删除成功"
  end

  def publish
    @job = Job.find(params[:id])
    # if @job.hidden?
      @job.publish!
    # end
    redirect_to admin_jobs_path
  end

  def hide
    @job = Job.find(params[:id])
    # if !@job.hidden?
      @job.hide!
    # end
    redirect_to admin_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :location, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_admin
    if !current_user.admin?
      flash[:warning] = "你不是管理员"
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all.where(:is_hidden => false).order("created_at DESC")
  end

  def show
    @job = Job.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:alert] = "good"
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_state(job)
    if job.hidden?
      content_tag(:i, "", class: "fa fa-lock")
    else
      content_tag(:i, "", class: "fa fa-globe")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module  FlashesHelper
  FLASH_CLASSES = { notice: "success", warning: "warning", alert: "danger" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym,key
  end

  def user_facing_flashes
    flash.to_hash.slice "notice", "warning", "alert"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def  render_job_time(job)
    job.created_at.to_s(:long)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/_form_job.html.erb
<%= simple_form_for [:admin, @job] do |f| %>

  <%= f.input :title %>
  <%= f.input :location %>
  <%= f.input :description %>
  <%= f.input :wage_lower_bound %>
  <%= f.input :wage_upper_bound %>
  <%= f.input :contact_email %>
  <%= f.input :is_hidden %>

  <%= f.submit "提交" %>

<% end %>

app/views/admin/jobs/edit.html.erb
<h1>编缉工作</h1>

<%= render "form_job" %>

app/views/admin/jobs/index.html.erb
<div class="container-fluid">
  <div class="pull-right">
    <%= link_to("新增工作", new_admin_job_path, class: "btn btn-primary btn-sm") %>
  </div>

  <table class="table table-bordered table-striped">
    <thead>
      <th>工作名称</th>
      <th>工作地点</th>
      <th>发布时间</th>
      <th colspan="3">管理选项</th>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td>
            <%= render_job_state(job) %>
            <%= link_to(job.title, admin_job_path(job)) %>
          </td>
          <td><%= job.location %></td>
          <td><%= job.created_at %></td>
          <td>
            <% if job.hidden? %>
              <%= link_to("publish", publish_admin_job_path(job), method: :post, class: "btn btn-info btn-xs") %>
            <% else %>
              <%= link_to("hide", hide_admin_job_path(job), method: :post, class: "btn btn-warning btn-xs") %>
            <% end %>
          </td>
          <td>
            <%= link_to("编缉", edit_admin_job_path(job),class: "btn btn-success btn-xs") %>
          </td>
          <td>
            <%= link_to("删除", admin_job_path(job), method: :delete, class: "btn btn-danger btn-xs") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/jobs/new.html.erb
<h1>新建工作</h1>

<%= render "form_job" %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,value| %>
    <div class="alert alert-datadismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container-fluid" style="margin-top:100px;">
  <p class="text-center">CopyRight ©2017
    <br>Design by 
    <a href="#">Michael</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Job</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to(content_tag(:i,'登录', class: "fa fa-sign-in"), new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user && current_user.admin? %>
                <li><%= link_to("后台管理", admin_jobs_path) %></li>
              <% end %>
              <li><%= link_to(content_tag(:i, '登出', class: "fa fa-sign-out"), destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/jobs/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <th>工作名称</th>
      <th>工作地点</th>
      <th>工资下限</th>
      <th>工资上限</th>
      <th>发布时间</th>
    </thead>
    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= link_to(job.title, job_path(job)) %></td>
          <td><%= job.location %></td>
          <td><%= job.wage_lower_bound %></td>
          <td><%= job.wage_upper_bound %></td>
          <td><%= render_job_time(job) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>

<p><%= simple_format(@job.description) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobCompetation</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello World</h1>